name: "Run unit tests"

on:
  workflow_call:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: ".mypy_cache"
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
      - name: Install dependencies
        run: |
          pdm sync
      - name: Test with pytest
        run: |
          pdm run pytest
